public enum EvenementsEnum : int
{
    Canette = 1,
    CoursMatin = 2,
    Epuisement = 3,
    JourFerie = 4,
    RdvMedecin = 5,
    Grippe = 6,
    ReunionProjet = 7,
    CoursAprem = 8,
    OuvertureCulturelle = 9,
    CoursClarife = 10,
    TpNotes = 11,
    ConferenceHeiEvenement = 12,
    SiesteRemplaceCours = 13,
    AbsenceBizarre = 14,
    RdvAvrin = 15,
    DejeunerAuRu = 16,
    PauseFaluche =17,
    SortieSport = 18,
    SoireeInte = 19,
    SportBDS = 20,
    BalHEI = 21,
    AfterworkHei = 22,
}