public enum ProbaEnum : int
{
   
    Canette = 10,
    CoursMatin = 20,
    Epuisement = 30,
    JourFerie = 10,
    RdvMedecin = 20,
    Grippe = 10,
    ReunionProjet = 5,
    CoursAprem = 50,
    OuvertureCulturelle = 30,
    CoursClarife = 10,
    TpNotes = 11,
    ConferenceHeiEvenement = 12,
    SiesteRemplaceCours = 13,
    AbsenceBizarre = 14,
    RdvAvrin = 15,
    DejeunerAuRu = 16,
    PauseFaluche = 17,
    SortieSport = 18,
    SoireeInte = 19,
    SportBDS = 20,
    BalHEI = 21,
    AfterworkHei = 22,
    Conference = 60,
    FrigoVide = 10,
}